// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace Finanzas2018.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Accion
    {

        [JsonProperty("quote")]
        public Quote Quote { get; set; }

        [JsonProperty("logo")]
        public Logo Logo { get; set; }
    }

    public partial class Logo
    {
        [DisplayName("Logo")]
        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public partial class Quote
    {

        [DisplayName("Simbolo")]
        [JsonProperty("symbol")]
        public string Symbol { get; set; }

        [DisplayName("Compañía")]
        [JsonProperty("companyName")]
        public string CompanyName { get; set; }

        [DisplayName("Precio")]
        [JsonProperty("latestPrice")]
        public double LatestPrice { get; set; }
    }

    public partial class Accion
    {
        public static Accion FromJson(string json) => JsonConvert.DeserializeObject<Accion>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Accion self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
